package(default_visibility = ["//visibility:public"])

cc_library(
  name = "Arduino",
  testonly = True,
  hdrs = ["//test/mock:Arduino.h"],
  strip_include_prefix = "",
  deps = [
    "@gtest//:gtest",
  ],
)
cc_library(
  name = "Wire",
  testonly = True,
  hdrs = ["//test/mock:Wire.h"],
  strip_include_prefix = "",
)
