package(default_visibility = ["//visibility:public"])

cc_library(
  name = "ds3231rtc",
  testonly = True,
  hdrs = ["ds3231rtc.h"],
  srcs = ["ds3231rtc.cpp"],
  deps = [
    "//test/mock:Arduino",
    "//test/mock:Wire",
  ],
)
